site_name: UnBeatables 2024
site_author: Unb
site_description: >-
  Git pages voltado para documentar bla bla

#site_url: https://lara-unb.io/unBeatables2024/

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: dark mode
      primary: green
      accent: green
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: light mode    
      primary: green
      accent: lime

nav:
  - Página Inicial: index.md

markdown_extensions:
  - tables
  - pymdownx.emoji
  - pymdownx.tasklist
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences

